apiVersion: v1
kind: Service
metadata:
  name: cas-acs-server
  labels:
    app: cas-acs-server
spec:
  ports:
    - name: cas-acs-server-service
      port: 8080
      targetPort: 8080
  selector:
    app: cas-acs-server
status:
  loadBalancer: LoadBalancer