name: Snapshot Release

on:
  pull_request:
  push:
    branches:
      - master

#Jobs to run
jobs:
  setup:
    if: startsWith(github.ref, 'refs/tags/v') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project-version

      - name: Show extracted Maven project version
        run: echo ${{ steps.project-version.outputs.version }}

  publish:
    if: startsWith(github.ref, 'refs/tags/v') != true && contains(needs.setup.steps.project-version.outputs.version, 'SNAPSHOT')
    runs-on: ubuntu-latest
    steps:
      - name: Build(Clean, Compile, Test, and Package) with Maven
        run: mvn -B clean install

      - name: Publish package
        run: |
          mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
