name: Snapshot Release

on:
  push:
    branches:
      - master

#Jobs to run
jobs:
  setup:
    if: startsWith(github.ref, 'refs/tags/v') != true
    runs-on: ubuntu-latest
    outputs:
      project-version: ${{steps.project-version.outputs.version}}
    steps:
      - uses: actions/checkout@v2
      - name: Release Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Extract Maven project version
        run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
        id: project-version

      - name: Show extracted Maven project version
        run: echo ${{steps.project-version.outputs.version}}

  publish:
    needs: [ setup ]
    if: contains(needs.setup.outputs.project-version, 'SNAPSHOT')
    runs-on: ubuntu-latest
    steps:
      - name: Print Project Version
        run: echo ${{needs.setup.outputs.project-version}}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Release Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build(Clean, Compile, Test, and Package) with Maven
        run: mvn -B clean install

      - name: Publish package
        run: |
          mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
