name: Snapshot Release

on:
  push:
    branches:
      - master

#Jobs
jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build(Clean, Compile, Test, and Package) with Maven
        run: mvn -B clean install

      - name: Publish package
        run: |
          mvn deploy -PossrhDeploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}